title=Google Apps on Kindle Fire Tablet
date=2016-06-28
type=post
status=published
tags=Android, Google, Amazon, Hardware
~~~~~~
Ben's birthday is approaching,
so I picked up the inexpensive
http://amzn.to/28Z9Jiq[Amazon Fire Tablet from 2015].
It's running FireOS 5.1.x.

He played with it running stock for a week or so,
using it to mostly read library books,
and of course, to play some games
from the Amazon Appstore.

Reading was the main purpose
to have the tablet,
but I also wanted it for communication
and organization.
That means getting the Google Apps installed on it.
The only things available
in the Amazon Appstore
were these shell apps
that were nothing more
than a wrapper
aronud a web pane,
so I needed to proceed
to install the Google Play framework
and app store.

Before even buying the tablet,
I had found some links,
so I was pretty sure it could be done.
I started with a
http://forum.xda-developers.com/amazon-fire/general/installing-google-framework-playstore-t3216122[post on XDA]
which got me the link
to an http://rootjunkysdl.com/files/Amazon%20Fire%205th%20gen/Amazon-Fire-5th-Gen-Install-Play-Store.zip[all-in-one ZIP] of everything I'd need.

It came with the APK files
and directions to run a Windows BAT file,
which obviously isn't going to happen
on any machine I have,
so I cracked open the BAT,
and followed the script running the important bits
by hand:

* Login to the tablet as the original login --
  Ben's secondary login didn't work.
* *Enable Developer Options* --
  Settings -> Device Options -> tap serial number serveral times,
  and the Developer Options will appear.
* *Enable USB Debugging* --
  Settings -> Device Options -> Developer Options -> Enable ADB to _Enabled_
* *Enable Side Loading* --
  Settings -> Device Options -> Developer Options -> Enable Untrusted Sources
* I was on a Mac, so the USB drivers were already good,
  and I had Android Developer Tools already installed.
* Unpack the all-in-one ZIP.
* Run the commands at the shell:
+
----
# see that tablet device is listed
adb devices
adb install com.google.android.gms-6.6.03_\(1681564-036\)-6603036-minAPI9.apk
adb install GoogleLoginService.apk
adb install GoogleServicesFramework.apk
adb shell pm grant com.google.android.gms android.permission.INTERACT_ACROSS_USERS
adb install com.android.vending-5.9.12-80391200-minAPI9.apk

# disable ads on cheap tablet, though I already paid to have it disabled.
adb shell pm hide com.amazon.kindle.kso
----

After those couple commands,
I found I had the Play Store icon,
and fired it up,
did the Play Services upgrade,
and started installing the Gmail, Calendar, Hangouts, and Keep.
I did find Inbox would crash after setup, but Gmail was fine.

