title=JBake
date=2016-01-05
type=post
status=published
tags=Technology, Computers, Blog
~~~~~~
I've moved the blog to a static site generated by
http://jbake.org/[JBake].
The source for the content lives in my
https://github.com/jflinchbaugh/techblog_content[techblog project in Github].

I initialized it with the Groovy templating engine and have started
customizing it.  I'll continue to customize it, and eventually break
out another instance of it for the photography blog.

I've been collecting a long list of (mostly technical) articles to
write, but replacing the old platform kept trumping my attempts to
write.  Hopefully, this can open the flood gates.

To make sure this thing is easy to update,
I keep a local clone of the repo, so I can update it any time
and push whenever I'm ready.  I have a shell script
scheduled to run on the server which basically does:

----
cd techblog
git pull | grep "Already" > /dev/null || jbake
----

That little bit of code
only runs `jbake`
if the `git pull` doesn't say "Already up-to-date".
That provided me a simple little "continuous integration" hook
that polls git for changes to trigger the build.
I'll probably use this trick in other places.

