title=JBake
date=2016-01-05
type=post
status=published
tags=Technology, Computers, Blog
~~~~~~
I've moved the blog to a static site generated by
http://jbake.org/[JBake].
The source for the content lives in my
https://github.com/jflinchbaugh/techblog_content[techblog project in Github],
so I have a full versioning of my content
for the small price of a git workflow.

I installed JBake using the familiar http://sdkman.io/[SDKMan]
that I already use to manage my Grails and Groovy installations.
I initialized it with the Groovy templating engine and have started
customizing the templates.

To make sure this thing is easy to update,
I keep a local clone of the repo, so I can update it any time
and push whenever I'm ready.  I have a shell script
scheduled to run on the server which basically does:

----
cd techblog
git pull | grep "Already" > /dev/null || jbake
----

That little bit of code
only runs `jbake`
if the `git pull` doesn't say "Already up-to-date".
That provided me a simple little "continuous integration" hook
that polls git for changes to trigger the build.
I'll probably use this trick in other places.

I brought all my old content from my old database
into the new platform using a quick little Groovy script
to dump out an HTML file for each article
including the header of metadata for JBake's use.
While most of these old articles will remain HTML,
I intend to use
http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoctor]
format for all the new stuff.

I've been collecting a long list
of (mostly technical) articles
to write,
but replacing the old platform
kept trumping my attempts to write.
Hopefully,
this move can open the flood gates,
and eventually,
I'll break out another instance
of it for the photography blog.
JBake should make it easy
and interesting to continue the blogs.
