title=No Sound on Boot and Login
date=2026-09-23
type=post
status=published
tags=Computers, Linux
~~~~~~

For forever,
I've been using a Lenovo IdeaPad
running GNOME Desktop
on Debian Unstable
I've enabled "linger" for my login,
so my services can start at boot,
instead of waiting for my login.
This is useful for quadlet podman containers
that run test services.
----
$ loginctl enable-linger
----

With this linger capability,
my sound services (pipewire and wireplumber)
start up right away too,
and it turns out they can often
race the initialization of the actual
sound card devices.
Wireplumber will start when there's
no sound device available,
so will only offer a "Dummy Output"
in my session until I restart pipewire
(systemctl --user restart pipewire).

I can ensure wireplumber waits
for the sound devices to be available
by configuring dependencies in systemd.

----
$ systemctl --user edit wireplumber.service

#
# Then add to that file:
# [Unit]
# After=sound.target
# Wants=sound.target
#

$ systemctl --user daemon-reload
----
