title=Reverse Proxy in shadow-cljs
date=2026-03-03
type=post
status=published
tags=3D-Printing, Amazon, Android, Blog, Blog-Code, Bolt-EV, Books, Clojure, Code, Computers, Cooking, Emacs, Entertainment, Food, Friends, Games, Google, Hardware, Home, Humor, Java, Linux, Mac, Mobile, Music, Podcasts, Politics, Recipe, Technology, Testing, Toys, Video, Web, Work
~~~~~~

I've broken my reverse proxy configuration
in shadow-cljs multiple times,
so I need a reminder for myself.

I have the server-side api running
in a container,
and the CLJS is running in shadow-cljs in dev mode.

With a `:proxy-url` set,
shadow-cljs will forward
any request it can't match
with a file
in the root
to teh other server.
This helps avoid Cross-Site-Request-Forgery failures
in the browser
during development.

----
 :dev-http {3000 {:root "public"
                  :proxy-url "http://localhost:7000/my-backend-service"}}
----

The important part
is to ensure
the URL lacks the trailing slash.
With the slash, I see lots of not-found errors
from the backend server
for everything but the default index.
